In [4]:
import pandas as pd

articles = pd.read_csv("Web_Page/Input Data/reference.csv")

In [5]:
journals=articles.groupby('First Author',as_index=False).count().sort_values(by='Title',ascending=False)
#journals.sort_values()
journals.head(20)

,First Author,Unnamed: 0,Authors,Citations,Date,Full Text Available,Journal,Stats,Summary,Title,...,Aluminum,Carbon,Copper,Graphite,Iron,Nickel,Silicon,Silver,Tantalum,Titanium
401,N Dukhan,13,13,13,13,13,13,13,13,13,...,5,0,0,0,0,0,0,0,0,0
178,ES Park,4,4,4,4,4,4,4,4,4,...,0,0,0,0,0,0,0,0,0,0
275,JF Rakow,4,4,4,4,4,4,4,4,4,...,1,0,0,0,0,0,0,0,0,0
52,AH Brothers,3,3,3,3,3,3,3,3,3,...,1,0,0,0,0,0,0,0,0,0
310,KC Leong,3,3,3,3,3,3,3,3,3,...,0,0,0,1,0,0,0,0,0,0
121,"CY Zhao, TJ Lu",3,3,3,3,3,3,3,3,3,...,0,0,0,0,3,0,0,0,0,0
346,"M Amani, M Ameri",3,3,3,3,3,3,3,3,3,...,0,0,0,0,2,0,0,0,0,0
386,"MAA Mendes, S Ray",3,3,3,3,3,3,3,3,3,...,0,0,0,0,0,0,0,0,0,0
532,T Braun,3,3,3,3,3,3,3,3,3,...,0,0,0,0,0,0,0,0,0,0
407,"N Michailidis, F Stergioudi",3,3,3,3,3,3,3,3,3,...,0,0,0,0,0,1,0,0,0,0
429,"P De Jaeger, C T'Joen, H Huisseune",2,2,2,2,2,2,2,2,2,...,2,0,0,0,0,0,0,0,0,0
428,"P De Jaeger, C T'Joen",2,2,2,2,2,2,2,2,2,...,2,0,0,0,0,0,0,0,0,0
559,"V Paserin, S Marcuson",2,2,2,2,2,2,2,2,2,...,0,0,0,0,0,2,0,0,0,0
561,VS Deshpande,2,2,2,2,2,2,2,2,2,...,0,0,0,0,0,0,0,0,0,0
96,"C Perrot, F Chevillotte",2,2,2,2,2,2,2,2,2,...,1,0,0,0,0,0,0,0,0,0
95,C Park,2,2,2,2,2,2,2,2,2,...,0,0,0,0,0,0,0,0,0,0
406,N Michailidis,2,2,2,2,2,2,2,2,2,...,0,0,0,0,0,0,0,0,0,0
408,"N Michailidis, F Stergioudi, H Omar",2,2,2,2,2,2,2,2,2,...,0,0,0,0,0,1,0,0,0,0
572,WS Sanders,2,2,2,2,2,2,2,2,2,...,0,0,0,0,0,0,0,0,0,0
237,"I Jin, LD Kenny",2,2,2,2,2,2,2,2,2,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
values=[]
labels=[]

for i in range(5):
    value=journals.iloc[i]['Authors']
    label = journals.iloc[i]['Journals']
    
    values.append(value)
    labels.append(label)
    
    i=i+1
    
print(values)
print(labels)

In [ ]:
filtered=articles[articles["Thermal Properties"]=="Thermal Properties"]
#gapminder_2002 = gapminder[gapminder['year']==2002]
filtered = filtered[filtered["Composition"]=="Aluminum"]
filtered.head(50)

In [ ]:
journals=filtered.groupby('Journals',as_index=False).count().sort_values(by='Title',ascending=False)
#journals.sort_values()
journals.head(50)